
["Spawn settings"]
	#As the value gets larger, the less razor tyrants will spawn naturally.
	RazorTyrantSpawnController = 500.0
	#You can set this value to choose whether this mob spawns naturally.
	IsTyrantSpawnNaturally = true

